{
    'name': 'HR Attendance Custom Extensions',
    'version': '19.0.1.3.47',
    'category': 'Human Resources/Attendances',
    'summary': 'Shamsieh attendance, fingerprint sync (Hikvision + ZKTeco), and face attendance',
    'author': 'Custom',
    'depends': ['hr', 'hr_attendance', 'hr_holidays', 'base_geolocalize', 'resource', 'mail'],
    'data': [
        'security/hr_attendance_custom_security.xml',
        'security/ir.model.access.csv',
        'data/resource_calendar_data.xml',
        'data/fingerprint_attendance_policy_data.xml',
        'data/ir_cron_data.xml',
        'views/res_config_settings_views.xml',
        'views/resource_calendar_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_employee_live_status_views.xml',
        'views/hr_attendance_views.xml',
        'views/fingerprint_attendance_policy_views.xml',
        'views/fingerprint_device_log_views.xml',
        'views/fingerprint_device_views.xml',
        'views/hr_attendance_daily_status_views.xml',
        'views/hr_employee_face_template_views.xml',
        'views/hr_employee_face_enroll_wizard_views.xml',
        'views/face_attendance_log_views.xml',
        'views/hr_attendance_report_views.xml',
        'views/hr_attendance_menus.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
    'assets': {
        'web.assets_backend': [
            'hr_attendance_custom_ext/static/src/**/*.js',
            'hr_attendance_custom_ext/static/src/**/*.xml',
        ],
    },
}
