{
    'name': 'HR Loans & Advances',
    'version': '19.0.1.0.2',
    'category': 'Human Resources/Payroll',
    'summary': 'Employee salary advances and loans with manager/HR approval',
    'author': 'Custom',
    'depends': [
        'hr',
        'mail',
        'hr_overtime_management',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'wizard/hr_advance_refuse_wizard_views.xml',
        'wizard/hr_loan_refuse_wizard_views.xml',
        'views/hr_employee_advance_views.xml',
        'views/hr_employee_loan_views.xml',
        'views/hr_loans_advances_menus.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
