{
    'name': 'CRM Custom Extensions',
    'version': '19.0.1.0.5',
    'category': 'Sales/CRM',
    'summary': 'Shamsieh CRM fields, security, teams, targets, and dashboards',
    'author': 'Custom',
    'depends': ['crm', 'sales_team', 'utm', 'mail'],
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
    'data': [
        'security/crm_custom_security.xml',
        'security/ir.model.access.csv',
        'data/crm_lead_sector_data.xml',
        'data/crm_lead_channel_data.xml',
        'data/crm_lead_sequence.xml',
        'data/crm_stage_data.xml',
        'data/utm_source_data.xml',
        'data/mail_activity_type_data.xml',
        'data/crm_team_data.xml',
        'data/crm_team_target_data.xml',
        'views/crm_lead_sector_views.xml',
        'views/crm_lead_views.xml',
        'views/crm_team_views.xml',
        'views/crm_team_target_views.xml',
        'views/crm_dashboard_views.xml',
        'views/crm_menus.xml',
        'data/crm_demo_users.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
    'assets': {
        'web.assets_backend': [
            'crm_custom_ext/static/src/crm_kanban.scss',
        ],
        'web.assets_web_dark': [
            'crm_custom_ext/static/src/crm_kanban.dark.scss',
        ],
    },
}
