[options]
admin_passwd = admin
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = Shamsieh@dev2025
addons_path = addons,extra_addons,odoo/addons
default_productivity_apps = True
http_port = 8069
