[options]
admin_passwd = admin
db_host = 127.0.0.1
db_port = 5432
db_user = antonanwer
db_password =
addons_path = addons,extra_addons,odoo/addons,/Users/antonanwer/odoo-dev/enterprise-19
default_productivity_apps = True
http_port = 8069
