from . import attendance_calendar_mixin
from . import resource_calendar_attendance
from . import hr_employee
from . import hr_attendance
from . import hr_attendance_daily_status
from . import fingerprint_attendance_policy
from . import fingerprint_device
from . import fingerprint_device_log
from . import face_attendance_log
from . import hr_employee_face_template
from . import res_company
from . import res_config_settings
from . import ir_http
