#!/usr/bin/env python3
"""Generate professional Arabic ar.po files for custom Odoo modules."""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SKIP_PATTERN = re.compile(
    r'^(?:[a-z][a-z0-9_]*\.){2,}[a-z0-9_.]+$|^[0-9,]+$'
)

PO_HEADER = '''# Translation of Odoo Server.
# Professional Arabic (ar) translations.
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 19.0\\n"
"Report-Msgid-Bugs-To: \\n"
"POT-Creation-Date: {date}\\n"
"PO-Revision-Date: {date}\\n"
"Last-Translator: Shamsieh\\n"
"Language-Team: Arabic\\n"
"Language: ar\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5);\\n"
'''

# fmt: off
TRANSLATIONS: dict[str, str] = {
    # --- Shared / common ---
    "Active": "نشط",
    "Inactive": "غير نشط",
    "Archived": "مؤرشف",
    "Cancel": "إلغاء",
    "Company": "الشركة",
    "Date": "التاريخ",
    "Date & Time": "التاريخ والوقت",
    "Cost": "التكلفة",
    "Manager": "المدير",
    "Department": "القسم",
    "Draft": "مسودة",
    "Employee": "الموظف",
    "Error": "خطأ",
    "Status": "الحالة",
    "State": "الحالة",
    "Submit": "إرسال",
    "Approved": "معتمد",
    "Refused": "مرفوض",
    "Refuse": "رفض",
    "Approve": "اعتماد",
    "Project": "المشروع",
    "Task": "المهمة",
    "Reference": "المرجع",
    "Reason": "السبب",
    "Comment": "ملاحظة",
    "Description": "الوصف",
    "Attachments": "المرفقات",
    "Print": "طباعة",
    "Technical": "تقني",
    "Shared": "مشترك",
    "New": "جديد",
    "Today": "اليوم",
    "This Month": "هذا الشهر",
    "Last Month": "الشهر الماضي",
    "Passed": "ناجح",
    "Failed": "فاشل",
    "Pending": "قيد الانتظار",
    "Debug": "تصحيح",
    "Logs": "السجلات",
    "Optional": "اختياري",
    "Country": "الدولة",
    "Progress": "التقدم",
    "Template": "القالب",
    "Stages": "المراحل",
    "Stage": "المرحلة",
    "Done": "منجز",
    "Review": "مراجعة",
    "Waiting": "في الانتظار",
    "To Do": "للتنفيذ",
    "In Progress": "قيد التنفيذ",
    "Notice": "تنبيه",
    "Validation": "تحقق",
    "Not allowed": "غير مسموح",

    # --- Attendance: punch & presence ---
    "Check In": "تسجيل الحضور",
    "Check Out": "تسجيل الانصراف",
    "Check out": "تسجيل الانصراف",
    "Break In": "بدء الاستراحة",
    "Break Out": "العودة من الاستراحة",
    "On Break": "في استراحة",
    "Working": "في العمل",
    "Checked Out": "تم تسجيل الانصراف",
    "Punch Type": "نوع التسجيل",
    "Punch History": "سجل التسجيلات",
    "Punch Time": "وقت التسجيل",
    "Work State": "حالة العمل",
    "Attendance": "الحضور",
    "Attendance Error": "خطأ في الحضور",
    "Attendance Source": "مصدر الحضور",
    "Attendance Status": "حالة الحضور",
    "Attendance Policy": "سياسة الحضور",
    "Attendance Policies": "سياسات الحضور",
    "Attendance Required": "الحضور إلزامي",
    "Attendance Location": "موقع الحضور",
    "Attendance &amp; Face Recognition": "الحضور والتعرف على الوجه",
    "Attendance punch could not be recorded.": "تعذر تسجيل الحضور.",
    "Connection lost. Attendance punch could not be recorded.": "انقطع الاتصال. تعذر تسجيل الحضور.",
    "Office day — use the fingerprint device to check in and out.": "يوم عمل في المكتب — استخدم جهاز البصمة لتسجيل الحضور والانصراف.",
    "Stay checked in": "البقاء مسجلاً للحضور",
    "Are you sure you want to check out now? You will not be able to check in again today.": "هل أنت متأكد من تسجيل الانصراف الآن؟ لن تتمكن من تسجيل الحضور مرة أخرى اليوم.",
    "Your device location is required to check in from the office.": "مطلوب موقع جهازك لتسجيل الحضور من المكتب.",
    "Manual attendance is not allowed on office schedule days. Please use the fingerprint device to check in and out.": "التسجيل اليدوي غير مسموح في أيام العمل بالمكتب. يرجى استخدام جهاز البصمة لتسجيل الحضور والانصراف.",
    "Manual attendance is not allowed on office schedule days. ": "التسجيل اليدوي غير مسموح في أيام العمل بالمكتب. يرجى استخدام جهاز البصمة لتسجيل الحضور والانصراف.",
    "You are already checked in.": "أنت مسجّل للحضور بالفعل.",
    "You have already checked in today. Only one check-in per day is allowed.": "لقد سجّلت حضورك اليوم بالفعل. يُسمح بتسجيل حضور واحد فقط في اليوم.",
    "You must be at the office to check in. You are %(distance).0f m away (allowed radius: %(radius)s m).": "يجب أن تكون في المكتب لتسجيل الحضور. أنت على بُعد %(distance).0f م (النطاق المسموح: %(radius)s م).",
    "Office geolocation is not configured. Please contact HR.": "لم يتم إعداد الموقع الجغرافي للمكتب. يرجى التواصل مع الموارد البشرية.",
    "Office check-in requires geolocation. Use the attendance menu instead.": "تسجيل الحضور من المكتب يتطلب الموقع الجغرافي. استخدم قائمة الحضور بدلاً من ذلك.",

    # --- Attendance: status ---
    "Present": "حاضر",
    "Absent": "غائب",
    "Late": "متأخر",
    "Late Minutes": "دقائق التأخير",
    "Early Leave": "مغادرة مبكرة",
    "Early Checkout": "انصراف مبكر",
    "Early Checkout Minutes": "دقائق الانصراف المبكر",
    "Incomplete": "غير مكتمل",
    "On Leave": "في إجازة",
    "On Approved Leave": "في إجازة معتمدة",
    "Public Holiday": "عطلة رسمية",
    "Is Public Holiday": "عطلة رسمية",
    "Missing Checkout": "انصراف غير مسجّل",
    "Daily Attendance Status": "حالة الحضور اليومية",
    "Working Schedule": "جدول العمل",

    # --- Attendance: sources ---
    "Fingerprint": "بصمة",
    "Face": "وجه",
    "Manual": "يدوي",
    "Kiosk": "كشك",
    "Systray": "شريط النظام",
    "Import": "استيراد",
    "PIN": "رمز PIN",

    # --- Attendance: reports & menus ---
    "Lateness Report": "تقرير التأخير",
    "Lateness Report (Attendance)": "تقرير التأخير (الحضور)",
    "Missing Attendance Report": "تقرير الغياب",
    "Missing Checkout Report": "تقرير الانصراف غير المسجّل",
    "Incomplete Attendance Report": "تقرير الحضور غير المكتمل",
    "Attendance Source Report": "تقرير مصدر الحضور",
    "Department Attendance Report": "تقرير حضور الأقسام",
    "PIN Attendance Logs": "سجل حضور رمز PIN",
    "Face Attendance Logs": "سجل حضور الوجه",
    "Face Templates": "قوالب الوجه",
    "Fingerprint Devices": "أجهزة البصمة",
    "Fingerprint Sync Logs": "سجلات مزامنة البصمة",
    "Fingerprint Device Logs Report": "تقرير سجلات جهاز البصمة",
    "Shamsieh Custom Attendance": "حضور شمسية المخصص",

    # --- Fingerprint device ---
    "Fingerprint Device": "جهاز البصمة",
    "Fingerprint Device Log": "سجل جهاز البصمة",
    "Fingerprint Device Manager": "مدير أجهزة البصمة",
    "Device IP": "عنوان IP للجهاز",
    "Port": "المنفذ",
    "API Type": "نوع واجهة API",
    "Hikvision ISAPI": "Hikvision ISAPI",
    "ZKTeco": "ZKTeco",
    "File Import (CSV)": "استيراد ملف (CSV)",
    "File Import": "استيراد ملف",
    "Custom API": "واجهة API مخصصة",
    "Auto Sync": "المزامنة التلقائية",
    "Automatic Sync": "المزامنة التلقائية",
    "Sync Logs": "سجلات المزامنة",
    "Sync Lookback (hours)": "نافذة جلب السجلات (ساعات)",
    "Device Timezone": "المنطقة الزمنية للجهاز",
    "Connection Timeout (s)": "مهلة الاتصال (ثانية)",
    "Sync Retries": "إعادة محاولات المزامنة",
    "Store All Device Events": "حفظ جميع أحداث الجهاز",
    "HTTP Listening": "الاستقبال عبر HTTP",
    "HTTP Listening Token": "رمز الاستقبال HTTP",
    "Allowed Source IPs": "عناوين IP المسموحة",
    "Last HTTP Push": "آخر إشعار HTTP",
    "Callback URL": "رابط الاستقبال",
    "Live HTTP Listening": "الاستقبال المباشر عبر HTTP",
    "Regenerate Token": "إعادة إنشاء الرمز",
    "Last Sync Checkpoint": "آخر نقطة تفتيش للمزامنة",
    "Polling Fallback Interval (minutes)": "فترة الاستطلاع الاحتياطي (دقائق)",
    "Import File": "ملف الاستيراد",
    "Idle": "خامل",
    "Running": "قيد التشغيل",
    "Success": "نجاح",
    "Processed": "تمت المعالجة",
    "Duplicate": "مكرر",
    "Ignored": "متجاهل",
    "Unmapped": "غير مربوط",
    "Unknown": "غير معروف",
    "Device": "الجهاز",
    "Event": "الحدث",
    "Event Date": "تاريخ الحدث",
    "Device User ID": "معرّف المستخدم في الجهاز",
    "External Log ID": "معرّف السجل الخارجي",
    "Biometric Device User ID": "معرّف المستخدم في جهاز البصمة",
    "Stored Employee Name": "اسم الموظف المخزّن",
    "Employee Name": "اسم الموظف",
    "Default Attendance Policy": "سياسة الحضور الافتراضية",
    "Company Default": "افتراضي الشركة",
    "Processing": "المعالجة",
    "Grace and Tolerance": "السماح والتسامح",
    "First / Last Scan": "أول / آخر مسح",
    "Alternating In / Out": "تناوب دخول / خروج",

    # --- Face ---
    "Face Provider": "مزود التعرف على الوجه",
    "Face Enrollment": "تسجيل الوجه",
    "Enroll Face": "تسجيل الوجه",
    "Enroll Face Template": "تسجيل قالب الوجه",
    "Enrollment Image": "صورة التسجيل",
    "Enrollment Photo": "صورة التسجيل",
    "Enroll": "تسجيل",
    "Reset": "إعادة تعيين",
    "View Templates": "عرض القوالب",
    "Face Verified": "تم التحقق من الوجه",
    "Face Match Threshold": "حد مطابقة الوجه",
    "Face Quality Checks": "فحوصات جودة الوجه",
    "Store Raw Face Images": "حفظ صور الوجه الأصلية",
    "Face Attendance Stub (Development)": "محاكاة حضور الوجه (تطوير)",
    "Enable Face Attendance Stub": "تفعيل محاكاة حضور الوجه",
    "Face Attendance Stub Enabled": "محاكاة حضور الوجه مفعّلة",
    "InsightFace Provider": "مزود InsightFace",
    "InsightFace Available": "InsightFace متاح",
    "Remote Face Attendance Allowed": "السماح بالحضور عن بُعد بالوجه",
    "Face Enrollment Status": "حالة تسجيل الوجه",
    "Not Enrolled": "غير مسجّل",
    "Enrolled": "مسجّل",
    "Face Enrolled At": "تاريخ تسجيل الوجه",
    "Face Enrolled By": "سجّل الوجه بواسطة",
    "Enrolled Face Image": "صورة الوجه المسجّلة",
    "Active Face Template": "قالب الوجه النشط",
    "Face Reference ID": "معرّف مرجع الوجه",
    "Face Template ID": "معرّف قالب الوجه",
    "Face Embedding (JSON)": "بصمة الوجه (JSON)",
    "Embedding": "البصمة",
    "Selfie Image": "صورة سيلفي",
    "Match Distance": "مسافة المطابقة",
    "Geo Distance (m)": "المسافة الجغرافية (م)",
    "Provider Response": "استجابة المزود",
    "Face verification failed.": "فشل التحقق من الوجه.",
    "Camera access is not available in this browser.": "الوصول إلى الكاميرا غير متاح في هذا المتصفح.",
    "Unable to access the camera. Please allow camera access and try again.": "تعذر الوصول إلى الكاميرا. يرجى السماح بالوصول والمحاولة مجدداً.",
    "'Face Verification'": "التحقق من الوجه",
    "Home PIN Check In": "تسجيل الحضور برمز PIN من المنزل",

    # --- PIN / home ---
    "Home PIN": "رمز PIN المنزلي",
    "Home Attendance PIN": "رمز PIN للحضور من المنزل",
    "Home Attendance PIN Hash": "تجزئة رمز PIN المنزلي",
    "Home Attendance PIN Set": "تم تعيين رمز PIN المنزلي",
    "Clear Home PIN": "مسح رمز PIN المنزلي",
    "PIN code": "رمز PIN",
    "PIN check-in failed.": "فشل تسجيل الحضور برمز PIN.",
    "PIN cannot be empty.": "لا يمكن أن يكون رمز PIN فارغاً.",
    "PIN must contain digits only.": "يجب أن يحتوي رمز PIN على أرقام فقط.",
    "PIN must be at least 4 digits.": "يجب أن يتكون رمز PIN من 4 أرقام على الأقل.",
    "Enter digits to set PIN": "أدخل أرقاماً لتعيين رمز PIN",

    # --- Office / geo ---
    "Office": "المكتب",
    "Home": "العمل عن بُعد",
    "Other": "أخرى",
    "Office Geo Reference Point": "نقطة المرجع الجغرافي للمكتب",
    "Office Latitude": "خط عرض المكتب",
    "Office Longitude": "خط طول المكتب",
    "Office Geo Radius": "نصف قطر الموقع الجغرافي للمكتب",
    "Office Geo Radius (meters)": "نصف قطر الموقع الجغرافي للمكتب (متر)",
    "Latitude": "خط العرض",
    "Longitude": "خط الطول",
    "Missing Checkout Tolerance": "سماحية الانصراف غير المسجّل",
    "Missing Checkout Tolerance (hours)": "سماحية الانصراف غير المسجّل (ساعات)",
    "Liveness Required": "التحقق الحيوي مطلوب",
    "Device &amp; Policy": "الجهاز والسياسة",
    "Hikvision Presence": "حالة الحضور Hikvision",

    # --- Settings help (short keys) ---
    "Tolerance": "السماحية",
    "Hours": "ساعات",
    "meters": "أمتار",
    "e.g. Asia/Amman": "مثال: Asia/Amman",
    "Shamsieh Standard 8h (08:00-16:00)": "دوام شمسية القياسي 8 ساعات (08:00-16:00)",

    # --- Errors attendance ---
    "Device IP is required.": "عنوان IP للجهاز مطلوب.",
    "Device username is required.": "اسم مستخدم الجهاز مطلوب.",
    "Failed to fetch device events: %s": "فشل جلب أحداث الجهاز: %s",
    "Connection failed: %s": "فشل الاتصال: %s",
    "Capability discovery failed: %s": "فشل اكتشاف إمكانيات الجهاز: %s",
    "Sync failed: %s": "فشلت المزامنة: %s",
    "Test connection is only implemented for Hikvision devices.": "اختبار الاتصال متاح فقط لأجهزة Hikvision.",
    "ZKTeco integration is not implemented yet.": "تكامل ZKTeco غير متوفر بعد.",
    "Unsupported API type: %s": "نوع API غير مدعوم: %s",
    "HTTP listening token must be at least 16 characters.": "يجب أن يتكون رمز الاستقبال HTTP من 16 حرفاً على الأقل.",
    "Fingerprint device sync failed": "فشلت مزامنة جهاز البصمة",
    "Unmapped fingerprint events": "أحداث بصمة غير مربوطة بموظف",
    "Missing device user ID": "معرّف مستخدم الجهاز مفقود",
    "Invalid event time": "وقت الحدث غير صالح",
    "No employee mapped for device user ID": "لا يوجد موظف مربوط بمعرّف المستخدم في الجهاز",
    "Enrollment image is required.": "صورة التسجيل مطلوبة.",
    "Only one active face template is allowed per employee.": "يُسمح بقالب وجه نشط واحد فقط لكل موظف.",
    "Remote face attendance is not allowed for this employee.": "حضور الوجه عن بُعد غير مسموح لهذا الموظف.",
    "Face verification is only required when working from home.": "التحقق من الوجه مطلوب فقط عند العمل عن بُعد.",
    "No active face template is enrolled for this employee.": "لا يوجد قالب وجه نشط مسجّل لهذا الموظف.",
    "Selfie image is required for face verification.": "صورة السيلفي مطلوبة للتحقق من الوجه.",
    "Face match confidence %(score).2f is below threshold %(threshold).2f.": "ثقة مطابقة الوجه %(score).2f أقل من الحد %(threshold).2f.",
    "Cannot perform %(action)s while employee is %(state)s.": "لا يمكن تنفيذ %(action)s بينما الموظف في حالة %(state)s.",

    # --- Overtime ---
    "Overtime": "العمل الإضافي",
    "Overtime Request": "طلب عمل إضافي",
    "Overtime Requests": "طلبات العمل الإضافي",
    "Overtime Type": "نوع العمل الإضافي",
    "Overtime Types": "أنواع العمل الإضافي",
    "Overtime Hours": "ساعات العمل الإضافي",
    "Overtime Hours (YTD)": "ساعات العمل الإضافي (منذ بداية السنة)",
    "Overtime Cost (YTD)": "تكلفة العمل الإضافي (منذ بداية السنة)",
    "Overtime Analysis": "تحليل العمل الإضافي",
    "Overtime Approval": "اعتماد العمل الإضافي",
    "My Requests": "طلباتي",
    "My Approvals": "موافقاتي",
    "To Approve": "بانتظار الاعتماد",
    "All Requests": "جميع الطلبات",
    "Configuration": "الإعدادات",
    "Submitted": "مُرسل",
    "Pending Approval": "بانتظار الاعتماد",
    "Manager Approved": "معتمد من المدير",
    "Upper Manager Approved": "معتمد من المدير الأعلى",
    "Cancelled": "ملغى",
    "Reset to Draft": "إعادة إلى مسودة",
    "Start Date & Time": "تاريخ ووقت البداية",
    "End Date & Time": "تاريخ ووقت النهاية",
    "Date &amp; Time": "التاريخ والوقت",
    "Overtime Hours": "ساعات العمل الإضافي",
    "Hourly Cost": "التكلفة بالساعة",
    "Total Cost": "التكلفة الإجمالية",
    "Company Currency": "عملة الشركة",
    "Company Branch": "فرع الشركة",
    "Employee Company": "شركة الموظف",
    "Current Approver": "المعتمد الحالي",
    "Approval History": "سجل الاعتمادات",
    "Approval Step": "خطوة الاعتماد",
    "Approvals": "الاعتمادات",
    "Approver": "المعتمد",
    "Decision Date": "تاريخ القرار",
    "Cost": "التكلفة",
    "Category": "الفئة",
    "Category &amp; Rate": "الفئة والمعدل",
    "Rate Multiplier": "مضاعف الأجر",
    "Regular": "يوم عمل عادي",
    "Weekend": "عطلة نهاية الأسبوع",
    "Day Off": "يوم عطلة",
    "Regular Overtime": "عمل إضافي يوم عادي",
    "Weekend Overtime": "عمل إضافي عطلة نهاية الأسبوع",
    "Day Off Overtime": "عمل إضافي يوم عطلة",
    "Regular Working Day": "يوم عمل عادي",
    "Weekend": "عطلة نهاية الأسبوع",
    "Day Off / Public Holiday": "يوم عطلة / عطلة رسمية",
    "Regular Overtime Type": "نوع العمل الإضافي (يوم عادي)",
    "Weekend Overtime Type": "نوع العمل الإضافي (عطلة نهاية الأسبوع)",
    "Day Off Overtime Type": "نوع العمل الإضافي (يوم عطلة)",
    "Weekend Weekdays": "أيام عطلة نهاية الأسبوع",
    "Daily Hours Warning Cap": "حد تحذير الساعات اليومية",
    "Daily Overtime Hours Warning Cap": "حد تحذير ساعات العمل الإضافي اليومية",
    "Working Hours per Month": "ساعات العمل الشهرية",
    "Hourly Cost Divisor": "مقسوم التكلفة بالساعة",
    "Timesheet Integration": "تكامل الجداول الزمنية",
    "Timesheet Line": "بند الجدول الزمني",
    "Generate Timesheet on Overtime Approval": "إنشاء جدول زمني عند اعتماد العمل الإضافي",
    "Link Overtime to Payroll": "ربط العمل الإضافي بالرواتب",
    "Payroll Integration": "تكامل الرواتب",
    "Push Overtime to Payslips": "إرسال العمل الإضافي إلى قسائم الرواتب",
    "Refuse Overtime Request": "رفض طلب العمل الإضافي",
    "Refuse Request": "رفض الطلب",
    "Please provide a reason for refusal...": "يرجى ذكر سبب الرفض...",
    "e.g. Regular Overtime": "مثال: عمل إضافي يوم عادي",
    "User: Own Overtime Requests": "مستخدم: طلبات العمل الإضافي الخاصة",
    "Officer: Overtime HR Approval": "مسؤول: اعتماد العمل الإضافي (الموارد البشرية)",
    "Administrator: Overtime Configuration": "مدير: إعدادات العمل الإضافي",
    "Department Manager": "مدير القسم",
    "Upper Manager": "المدير الأعلى",
    "HR Officer": "مسؤول الموارد البشرية",
    "To Approve": "بانتظار الاعتماد",
    "Overtime": "العمل الإضافي",

    # Overtime errors
    "A refusal reason is required.": "سبب الرفض مطلوب.",
    "An employee must be set before submitting.": "يجب تحديد الموظف قبل الإرسال.",
    "Only draft requests can be submitted.": "يمكن إرسال الطلبات في حالة المسودة فقط.",
    "Only cancelled or refused requests can be reset to draft.": "يمكن إعادة الطلبات الملغاة أو المرفوضة فقط إلى مسودة.",
    "Approved or refused requests cannot be cancelled.": "لا يمكن إلغاء الطلبات المعتمدة أو المرفوضة.",
    "No pending approval step found.": "لم يتم العثور على خطوة اعتماد قيد الانتظار.",
    "You are not allowed to approve this request.": "غير مسموح لك باعتماد هذا الطلب.",
    "You are not allowed to refuse this request.": "غير مسموح لك برفض هذا الطلب.",
    "You can only modify your own overtime requests.": "يمكنك تعديل طلبات العمل الإضافي الخاصة بك فقط.",
    "The selected approval step does not belong to this request.": "خطوة الاعتماد المحددة لا تنتمي إلى هذا الطلب.",
    "End date & time must be after start date & time.": "يجب أن يكون تاريخ ووقت النهاية بعد تاريخ ووقت البداية.",
    "The rate multiplier must be strictly positive.": "يجب أن يكون مضاعف الأجر أكبر من صفر.",
    "The task must belong to the selected project.": "يجب أن تنتمي المهمة إلى المشروع المحدد.",
    "No approval chain could be resolved for this employee.": "تعذر تحديد سلسلة الاعتماد لهذا الموظف.",
    "No HR officer is configured for overtime approval. ": "لم يتم إعداد مسؤول موارد بشرية لاعتماد العمل الإضافي.",
    "Overtime request submitted for approval.": "تم إرسال طلب العمل الإضافي للاعتماد.",
    "Approval chain is incomplete: no HR stage found. ": "سلسلة الاعتماد غير مكتملة: لم يتم العثور على مرحلة الموارد البشرية.",
    "Warning: overtime hours (%.2f) exceed the daily cap (%.2f).": "تحذير: ساعات العمل الإضافي (%.2f) تتجاوز الحد اليومي (%.2f).",
    "Overtime request %(ref)s requires your approval.": "طلب العمل الإضافي %(ref)s يتطلب اعتمادك.",
    "Request refused by %(user)s: %(reason)s": "تم رفض الطلب بواسطة %(user)s: %(reason)s",
    "Only one active overtime type is allowed per category for %(company)s. ": "يُسمح بنوع عمل إضافي نشط واحد فقط لكل فئة في %(company)s.",
    "No overtime type could be determined for this date. ": "تعذر تحديد نوع العمل الإضافي لهذا التاريخ.",
    "The company must match the employee\\'s company (%(company)s).": "يجب أن تطابق الشركة شركة الموظف (%(company)s).",
    "This overtime action is not allowed.": "هذا الإجراء غير مسموح لطلبات العمل الإضافي.",
    "This overtime record uses a company that is not in your Allowed Companies…": "سجل العمل الإضافي هذا يستخدم شركة غير مدرجة في الشركات المسموح لك بها…",

    # Overtime help texts
    "Applied on regular working days (Sunday–Thursday by default).": "يُطبّق في أيام العمل العادية (الأحد–الخميس افتراضياً).",
    "Applied when overtime falls on a configured weekend day.": "يُطبّق عندما يقع العمل الإضافي في يوم عطلة نهاية أسبوع مُعدّ.",
    "Applied when overtime falls on a public holiday or calendar day off.": "يُطبّق عندما يقع العمل الإضافي في عطلة رسمية أو يوم عطلة في التقويم.",
    "Automatically set from the date: regular working day, weekend, or company public holiday (e.g. Eid).": "يُحدَّد تلقائياً من التاريخ: يوم عمل عادي، عطلة نهاية أسبوع، أو عطلة رسمية للشركة (مثل العيد).",
    "Calendar date derived from the start datetime (used for filters and reports).": "تاريخ التقويم مستخرج من تاريخ ووقت البداية (للفلاتر والتقارير).",
    "Comma-separated weekday numbers (Monday=0 … Sunday=6). ": "أرقام أيام الأسبوع مفصولة بفواصل (الاثنين=0 … الأحد=6).",
    "Display a warning when a single request exceeds this number of hours.": "عرض تحذير عندما يتجاوز طلب واحد هذا العدد من الساعات.",
    "Each company branch should have exactly one active type per category. ": "يجب أن يكون لكل فرع شركة نوع نشط واحد فقط لكل فئة.",
    "Fallback divisor to derive hourly cost from monthly contract wage (wage / hours).": "مقسوم احتياطي لاشتقاق التكلفة بالساعة من الراتب الشهري (الراتب / الساعات).",
    "Install the payroll glue module to push approved overtime costs to payslips.": "ثبّت وحدة ربط الرواتب لإرسال تكاليف العمل الإضافي المعتمد إلى قسائم الرواتب.",
    "Leave empty only for shared template records. Each branch should have its own set.": "اتركه فارغاً فقط للسجلات المشتركة. يجب أن يكون لكل فرع مجموعته الخاصة.",
    "Pay rate multiplier applied to the base hourly cost (e.g. 1.5 for time-and-a-half).": "مضاعف الأجر المطبّق على التكلفة الأساسية بالساعة (مثل 1.5 لساعة ونصف).",
    "Technical code used internally (regular, weekend, holiday).": "رمز تقني داخلي (عادي، عطلة نهاية أسبوع، عطلة).",
    "Timesheet projects for your company (or shared across companies).": "مشاريع الجداول الزمنية لشركتك (أو مشتركة بين الشركات).",
    "Automatically create a timesheet line when overtime is fully approved.": "إنشاء بند جدول زمني تلقائياً عند اعتماد العمل الإضافي بالكامل.",
    "Rate applied on normal working days. Change the multiplier in Overtime → Configuration → Overtime Types.": "المعدل المطبّق في أيام العمل العادية. غيّر المضاعف من العمل الإضافي ← الإعدادات ← أنواع العمل الإضافي.",
    "Rate applied on weekend days (see weekdays below).": "المعدل المطبّق في أيام عطلة نهاية الأسبوع (انظر أيام الأسبوع أدناه).",
    "Rate applied on public holidays and calendar days off.": "المعدل المطبّق في العطل الرسمية وأيام العطلة في التقويم.",
    "Weekdays treated as weekend overtime (Monday=0 … Sunday=6). Default: 4,5 = Friday &amp; Saturday.": "أيام الأسبوع المعاملة كعطلة نهاية أسبوع (الاثنين=0 … الأحد=6). الافتراضي: 4,5 = الجمعة والسبت.",
    "Show a warning when a request exceeds this number of hours.": "عرض تحذير عندما يتجاوز الطلب هذا العدد من الساعات.",
    "Monthly working hours used to convert contract wage to hourly cost (wage ÷ hours).": "ساعات العمل الشهرية لتحويل راتب العقد إلى تكلفة بالساعة (الراتب ÷ الساعات).",
    "Employees can create and submit their own overtime requests.": "يمكن للموظفين إنشاء وإرسال طلبات العمل الإضافي الخاصة بهم.",
    "HR officers perform final approval on overtime requests.": "يقوم مسؤولو الموارد البشرية بالاعتماد النهائي لطلبات العمل الإضافي.",
    "Full access to overtime types and configuration settings.": "وصول كامل لأنواع العمل الإضافي وإعدادات التكوين.",

    # Overtime security rules
    "Overtime Request: employee read own": "طلب عمل إضافي: قراءة الموظف لطلباته",
    "Overtime Request: employee write draft": "طلب عمل إضافي: كتابة الموظف للمسودة",
    "Overtime Request: employee cancel submitted": "طلب عمل إضافي: إلغاء الموظف للطلب المُرسل",
    "Overtime Request: employee reset refused/cancelled": "طلب عمل إضافي: إعادة الموظف للمرفوض/الملغى",
    "Overtime Request: current approver": "طلب عمل إضافي: المعتمد الحالي",
    "Overtime Request: HR officer read all": "طلب عمل إضافي: قراءة مسؤول HR للكل",
    "Overtime Request: HR officer write at HR stage": "طلب عمل إضافي: كتابة مسؤول HR في مرحلة HR",
    "Overtime Request: administrator full access": "طلب عمل إضافي: وصول كامل للمدير",
    "Overtime Request: multi-company": "طلب عمل إضافي: متعدد الشركات",
    "Overtime Type: multi-company": "نوع العمل الإضافي: متعدد الشركات",

    # Overtime payroll
    "Payslip Input": "مدخل قسيمة الراتب",

    # --- Project ---
    "Project Dashboard": "لوحة معلومات المشاريع",
    "Projects Overview": "نظرة عامة على المشاريع",
    "Projects by Stage": "المشاريع حسب المرحلة",
    "Projects by Manager": "المشاريع حسب المدير",
    "Projects by Project Manager": "المشاريع حسب مدير المشروع",
    "Projects by Country": "المشاريع حسب الدولة",
    "Project Progress %": "نسبة تقدم المشروع %",
    "Progress %": "نسبة التقدم %",
    "Progress Range": "نطاق التقدم",
    "0% - 20%": "من 0٪ إلى 20٪",
    "20% - 50%": "من 20٪ إلى 50٪",
    "50% - 80%": "من 50٪ إلى 80٪",
    "80% - 100%": "من 80٪ إلى 100٪",
    "Overdue Tasks": "مهام متأخرة",
    "Tasks by Stage": "المهام حسب المرحلة",
    "Timesheet by Employee": "الجدول الزمني حسب الموظف",
    "Timesheet by Project": "الجدول الزمني حسب المشروع",
    "Task Templates": "قوالب المهام",
    "Task Template": "قالب المهام",
    "Task Stages": "مراحل المهام",
    "Project Stage": "مرحلة المشروع",
    "Workflow Template": "قالب سير العمل",
    "Workflow template": "قالب سير العمل",
    "Stage Template": "قالب المراحل",
    "Add Standard Stages": "إضافة مراحل قياسية",
    "Counts as Done": "يُحسب منجزاً",
    "Closing Stage": "مرحلة الإغلاق",
    "Folded in Kanban": "مطوي في كانبان",
    "Estimated Hours": "الساعات المقدرة",
    "Spent Hours": "الساعات المنفقة",
    "Remaining Hours": "الساعات المتبقية",
    "Allocated Until": "مخصص حتى",
    "Time Remaining Until": "الوقت المتبقي حتى",
    "Sales Team": "فريق المبيعات",
    "Location &amp; Team": "الموقع والفريق",
    "Implementation Project Template": "قالب مشروع التنفيذ",
    "Website Project Template": "قالب مشروع الموقع",
    "CRM Setup Template": "قالب إعداد CRM",
    "Project Edit Only": "تعديل المشاريع فقط",
    "Project Create/Move": "إنشاء/نقل المشاريع",
    "Project Manager": "مدير المشروع",
    "Choose a workflow template…": "اختر قالب سير العمل…",
    "Select country": "اختر الدولة",
    "e.g. To Do": "مثال: للتنفيذ",
    "e.g. Website Delivery Workflow": "مثال: سير عمل تسليم الموقع",
    "Stage name (e.g. In Progress)": "اسم المرحلة (مثال: قيد التنفيذ)",
    "When should this template be used?": "متى يُستخدم هذا القالب؟",
    "this item": "هذا العنصر",
    "You need Project Create/Move or Manager rights to create projects.": "تحتاج صلاحية إنشاء/نقل المشاريع أو مدير المشروع لإنشاء مشاريع.",
    "The task template cannot be changed after it has been applied.": "لا يمكن تغيير قالب المهام بعد تطبيقه.",
    "This template already has stages. Edit them in the list or remove them first.": "هذا القالب يحتوي على مراحل بالفعل. عدّلها في القائمة أو احذفها أولاً.",
    "You cannot move tasks between stages with your current access level.": "لا يمكنك نقل المهام بين المراحل بمستوى صلاحياتك الحالي.",
    "This action is not allowed.": "هذا الإجراء غير مسموح.",
    "You don": "لا تملك",
    "Project Task: Edit Only users (write access)": "مهمة المشروع: مستخدمو التعديل فقط (صلاحية الكتابة)",
    "Project: Create/Move can create projects": "المشروع: إنشاء/نقل يمكنه إنشاء المشاريع",
    "Marks this project stage as a closing/completed stage.": "يحدد مرحلة المشروع كمرحلة إغلاق/إكمال.",
    "Completed tasks / total tasks × 100 (tasks in a closing stage count as done).": "المهام المنجزة / إجمالي المهام × 100 (المهام في مرحلة الإغلاق تُحسب منجزة).",
    "Planned date and time when allocated work on this project should be completed.": "التاريخ والوقت المخطط لإكمال العمل المخصص على هذا المشروع.",
    "Planned date and time when allocated work on this task should be completed.": "التاريخ والوقت المخطط لإكمال العمل المخصص على هذه المهمة.",
    "Select a template at project creation to auto-generate workflow stages (tasks are optional).": "اختر قالباً عند إنشاء المشروع لإنشاء مراحل سير العمل تلقائياً (المهام اختيارية).",
    "When enabled, tasks in this stage count as completed for the project progress % (e.g. Done or Completed).": "عند التفعيل، تُحسب المهام في هذه المرحلة منجزة لنسبة تقدم المشروع % (مثل منجز أو مكتمل).",
    "When enabled, tasks moved to this stage are treated as completed and increase the project progress %.": "عند التفعيل، تُعامل المهام المنقولة إلى هذه المرحلة كمنجزة وتزيد نسبة تقدم المشروع %.",

    # Cron jobs
    "Fingerprint: Sync All Devices": "البصمة: مزامنة جميع الأجهزة",
    "Fingerprint: Purge Old Raw Payloads": "البصمة: حذف البيانات الخام القديمة",
    "Attendance: Generate Daily Attendance Status": "الحضور: إنشاء حالة الحضور اليومية",
    "Attendance: Recompute Late/Early Status": "الحضور: إعادة حساب حالة التأخير/المغادرة المبكرة",
    "Attendance: Flag Missing Checkouts": "الحضور: تمييز الانصراف غير المسجّل",

    # Security rules attendance
    "Fingerprint Device: multi-company": "جهاز البصمة: متعدد الشركات",
    "Fingerprint Device Log: multi-company": "سجل جهاز البصمة: متعدد الشركات",
    "Face Attendance Log: own records": "سجل حضور الوجه: السجلات الخاصة",
    "Face Attendance Log: HR officers all": "سجل حضور الوجه: مسؤولو HR للكل",
    "Daily Attendance Status: multi-company": "حالة الحضور اليومية: متعدد الشركات",
    "Employee Face Template: multi-company": "قالب وجه الموظف: متعدد الشركات",

    # Long help strings attendance
    "Poll the device over the network on a schedule. ": "استطلاع الجهاز عبر الشبكة وفق جدول زمني.",
    "When HTTP listening is active and receiving events, polling is skipped. ": "عند تفعيل الاستقبال HTTP واستقبال الأحداث، يُتخطى الاستطلاع.",
    "When enabled, the device pushes access events to Odoo in real time. ": "عند التفعيل، يرسل الجهاز أحداث الدخول إلى Odoo في الوقت الفعلي.",
    "When enabled, door/system events are saved with state Ignored. ": "عند التفعيل، تُحفظ أحداث الباب/النظام بحالة متجاهل.",
    "When enabled, enrollment images may be stored as attachments.": "عند التفعيل، قد تُحفظ صور التسجيل كمرفقات.",
    "Comma-separated IPs allowed to POST events (defaults to device IP when enabled).": "عناوين IP المسموح لها بإرسال الأحداث مفصولة بفواصل (افتراضياً IP الجهاز عند التفعيل).",
    "Comma-separated attendance sources for the day.": "مصادر الحضور لليوم مفصولة بفواصل.",
    "Days to keep raw_payload on device logs before clearing (0 = keep forever).": "أيام الاحتفاظ بالبيانات الخام في سجلات الجهاز قبل الحذف (0 = الاحتفاظ دائماً).",
    "How many hours back to fetch access events on each sync.": "عدد الساعات للخلف لجلب أحداث الدخول في كل مزامنة.",
    "IANA timezone of the device clock (e.g. Asia/Amman). ": "المنطقة الزمنية IANA لساعة الجهاز (مثال: Asia/Amman).",
    "Narrow event fetch window after successful sync.": "تضييق نافذة جلب الأحداث بعد مزامنة ناجحة.",
    "Last punch recorded for this attendance day.": "آخر تسجيل مسجّل ليوم الحضور هذا.",
    "Hours after scheduled calendar end before an open attendance is flagged as missing checkout.": "ساعات بعد نهاية الدوام المجدول قبل تمييز الحضور المفتوح كانصراف غير مسجّل.",
    "Defines where employees are expected to work for this schedule line.": "يحدد مكان العمل المتوقع للموظفين في سطر الجدول هذا.",
    "Date is a company or calendar public holiday.": "التاريخ عطلة رسمية للشركة أو التقويم.",
    "Employee had a validated time off request on this date.": "كان لدى الموظف طلب إجازة معتمد في هذا التاريخ.",
    "User ID on the fingerprint device; used to map device logs to this employee.": "معرّف المستخدم في جهاز البصمة؛ يُستخدم لربط سجلات الجهاز بهذا الموظف.",
    "Odoo employee name at sync time (not the device scanner label).": "اسم الموظف في Odoo وقت المزامنة (وليس تسمية الماسح في الجهاز).",
    "Live work state from the Hikvision fingerprint bridge.": "حالة العمل المباشرة من جسر بصمة Hikvision.",
    "Home attendance PIN. Leave unchanged on save to keep the current value.": "رمز PIN للحضور من المنزل. اتركه دون تغيير عند الحفظ للإبقاء على القيمة الحالية.",
    "Displayed PIN value configured for home attendance.": "قيمة رمز PIN المعروضة المُعدّة للحضور من المنزل.",
    "Allows remote check-in/out via face verification (§9).": "يسمح بتسجيل الحضور/الانصراف عن بُعد عبر التحقق من الوجه.",
    "Allowed geolocation distance in meters from the office reference point.": "المسافة الجغرافية المسموحة بالأمتار من نقطة مرجع المكتب.",
    "Reference latitude for office check-in geofencing.": "خط عرض المرجع لتسييج الموقع الجغرافي لتسجيل الحضور من المكتب.",
    "Reference longitude for office check-in geofencing.": "خط طول المرجع لتسييج الموقع الجغرافي لتسجيل الحضور من المكتب.",
    "Minimum cosine similarity score required for face verification.": "الحد الأدنى لدرجة التشابه الجيبي المطلوبة للتحقق من الوجه.",
    "Reject blurry, low-resolution, or small-face images.": "رفض الصور الضبابية أو منخفضة الدقة أو الوجوه الصغيرة.",
    "Development only: auto-pass face verification without external provider.": "للتطوير فقط: اجتياز التحقق من الوجه تلقائياً دون مزود خارجي.",
    "Reserved for future advanced liveness detection.": "محجوز للكشف الحيوي المتقدم مستقبلاً.",
    "Active internal face template reference.": "مرجع قالب الوجه الداخلي النشط.",
    "Optional external face enrollment reference.": "مرجع تسجيل وجه خارجي اختياري.",
    "Optional external reference": "مرجع خارجي اختياري",
    "Optional notes about lighting, angle, or device used…": "ملاحظات اختيارية عن الإضاءة أو الزاوية أو الجهاز المستخدم…",
    "CSV for file_import API type: external_id,device_user_id,punch_time,punch_type": "CSV لنوع API استيراد الملف: external_id,device_user_id,punch_time,punch_type",
    "Company %(company)s already has a default policy (%(policy)s).": "الشركة %(company)s لديها سياسة افتراضية بالفعل (%(policy)s).",
    "Device %(device)s: %(error)s": "الجهاز %(device)s: %(error)s",
    "%(count)s event(s) have no employee mapping on device %(device)s.": "%(count)s حدث/أحداث غير مربوطة بموظف على الجهاز %(device)s.",
    "Fetched %(fetched)s | stored %(stored)s | ignored %(ignored)s | duplicates %(duplicates)s | unmapped %(unmapped)s | skipped %(skipped)s": "تم جلب %(fetched)s | تخزين %(stored)s | تجاهل %(ignored)s | مكرر %(duplicates)s | غير مربوط %(unmapped)s | تخطي %(skipped)s",
    "Fetched %(fetched)s | stored %(stored)s | ignored %(ignored)s | ": "تم جلب %(fetched)s | تخزين %(stored)s | تجاهل %(ignored)s | ",
    "%(message)s Install optional Python packages from requirements-face.txt.": "%(message)s ثبّت حزم Python الاختيارية من requirements-face.txt.",
    "Your employee record is linked to %(company)s, but that company is not in your ": "سجل الموظف مربوط بـ %(company)s، لكن هذه الشركة غير مدرجة في ",
    "The project ": "المشروع ",
    "Configure fingerprint devices and run manual sync.": "إعداد أجهزة البصمة وتشغيل المزامنة اليدوية.",
    "Currently Working": "يعمل حالياً",
    "Last 7 Days": "آخر 7 أيام",
    "Before": "قبل",
    "Since": "منذ",
    "Total today": "إجمالي اليوم",
    "Verifying...": "جارٍ التحقق...",
    "Capture & Check In": "التقاط وتسجيل الحضور",
    "Checking...": "جارٍ التحقق...",
    "Check In with PIN": "تسجيل الحضور برمز PIN",
    "Position your face in the frame to verify your identity before checking in.": "ضع وجهك داخل الإطار للتحقق من هويتك قبل تسجيل الحضور.",
    "Enter your personal home attendance PIN to complete check in.": "أدخل رمز PIN الشخصي للحضور من المنزل لإتمام تسجيل الحضور.",
    "Face Verification": "التحقق من الوجه",
    "HR officers perform final overtime approval and can see all requests.": "يقوم مسؤولو الموارد البشرية بالاعتماد النهائي لطلبات العمل الإضافي ويمكنهم عرض جميع الطلبات.",
    "Full access to overtime types, settings, and all requests.": "وصول كامل لأنواع العمل الإضافي والإعدادات وجميع الطلبات.",
    "You don't have %(permission)s permission on %(resource)s.": "ليس لديك صلاحية %(permission)s على %(resource)s.",
    "Build your workflow.": "ابنِ سير عملك.",
    "CRM Setup Template": "قالب إعداد CRM",
    "Implementation Project Template": "قالب مشروع التنفيذ",
    "Website Project Template": "قالب مشروع الموقع",
    "End date & time must be after start date & time.": "يجب أن يكون تاريخ ووقت النهاية بعد تاريخ ووقت البداية.",
    "The task must belong to the selected project.": "يجب أن تنتمي المهمة إلى المشروع المحدد.",
    "Only draft requests can be submitted.": "يمكن إرسال طلبات المسودة فقط.",
    "An employee must be set before submitting.": "يجب تحديد الموظف قبل الإرسال.",
    "No approval chain could be resolved for this employee.": "تعذّر تحديد سلسلة الاعتماد لهذا الموظف.",
    "Approved or refused requests cannot be cancelled.": "لا يمكن إلغاء الطلبات المعتمدة أو المرفوضة.",
    "Only cancelled or refused requests can be reset to draft.": "يمكن إعادة الطلبات الملغاة أو المرفوضة إلى المسودة فقط.",
    "No pending approval step found.": "لم يُعثر على خطوة اعتماد معلّقة.",
    "My Approvals": "موافقاتي",
    "Pending Approval": "بانتظار الاعتماد",
    "Role": "الدور",
    "Decision Date": "تاريخ القرار",
    "Approvals": "الموافقات",
    "Overtime Requests": "طلبات العمل الإضافي",
    "Cancelled": "ملغى",
    "Name": "الاسم",
    "You can only modify your own overtime requests.": "يمكنك تعديل طلبات العمل الإضافي الخاصة بك فقط.",
    "You are not allowed to approve this request.": "غير مسموح لك باعتماد هذا الطلب.",
    "You are not allowed to refuse this request.": "غير مسموح لك برفض هذا الطلب.",
    "Refuse Request": "رفض الطلب",
    "The rate multiplier must be strictly positive.": "يجب أن يكون مضاعف المعدل موجباً بشكل صارم.",
    "Request refused by %(user)s: %(reason)s": "تم رفض الطلب من قِبل %(user)s: %(reason)s",
    "Overtime request submitted for approval.": "تم إرسال طلب العمل الإضافي للاعتماد.",
    "Add as many stages as you need…": "أضف المراحل التي تحتاجها…",
    "Create a stage template": "إنشاء قالب مراحل",
    "Give it a name, add your stages…": "أعطه اسماً، أضف مراحلك…",
}
# fmt: on

EXTRA_BY_MODULE: dict[str, dict[str, str]] = {
    "hr_overtime_management": {
        "Create your first overtime request": "أنشئ أول طلب عمل إضافي",
        "Submit overtime hours for manager and HR approval.": "أرسل ساعات العمل الإضافي لاعتماد المدير والموارد البشرية.",
        "No overtime waiting for your approval": "لا يوجد عمل إضافي بانتظار اعتمادك",
        "Requests appear here when you are the active approver in the chain.": "تظهر الطلبات هنا عندما تكون المعتمد النشط في السلسلة.",
        "Overtime Request": "طلب عمل إضافي",
        "Employee:": "الموظف:",
        "Department:": "القسم:",
        "Manager:": "المدير:",
        "Date:": "التاريخ:",
        "Start:": "البداية:",
        "End:": "النهاية:",
        "Hours:": "الساعات:",
        "Project:": "المشروع:",
        "Task:": "المهمة:",
        "Type:": "النوع:",
        "Status:": "الحالة:",
        "Hourly Cost:": "التكلفة بالساعة:",
        "Total Cost:": "التكلفة الإجمالية:",
        "Description:": "الوصف:",
        "Approval Trail": "مسار الاعتماد",
        "Role": "الدور",
        "Approver": "المعتمد",
        "Status": "الحالة",
        "Date": "التاريخ",
        "Comment": "ملاحظة",
        "Overtime - %s": "عمل إضافي - %s",
    },
    "project_custom_ext": {
        "Overview": "نظرة عامة",
        "You don't have %(permission)s permission on %(resource)s.": "ليس لديك صلاحية %(permission)s على %(resource)s.",
        "Can edit projects and tasks but cannot create projects or move tasks between stages.": "يمكنه تعديل المشاريع والمهام لكن لا يمكنه إنشاء مشاريع أو نقل المهام بين المراحل.",
        "Can create projects and move tasks between stages.": "يمكنه إنشاء المشاريع ونقل المهام بين المراحل.",
        "Full project management including configuration and deletion.": "إدارة كاملة للمشاريع بما في ذلك الإعدادات والحذف.",
        "Standard ERP / system implementation workflow stages.": "مراحل سير عمل تنفيذ ERP / النظام القياسية.",
        "Website design, development, and delivery workflow stages.": "مراحل سير عمل تصميم وتطوير وتسليم الموقع.",
        "CRM pipeline and setup workflow stages.": "مراحل سير عمل خط أنابيب CRM والإعداد.",
    },
    "hr_attendance_custom_ext": {
        "InsightFace (self-hosted)": "InsightFace (استضافة ذاتية)",
        "Face Provider: InsightFace (self-hosted)": "مزود الوجه: InsightFace (استضافة ذاتية)",
        "Monday Morning": "صباح الاثنين",
        "Tuesday Morning": "صباح الثلاثاء",
        "Wednesday Morning": "صباح الأربعاء",
        "Thursday Morning": "صباح الخميس",
        "Friday Morning": "صباح الجمعة",
        "Monday Lunch": "غداء الاثنين",
        "Tuesday Lunch": "غداء الثلاثاء",
        "Wednesday Lunch": "غداء الأربعاء",
        "Thursday Lunch": "غداء الخميس",
        "Friday Lunch": "غداء الجمعة",
        "Monday Afternoon": "بعد الظهر الاثنين",
        "Tuesday Afternoon": "بعد الظهر الثلاثاء",
        "Wednesday Afternoon": "بعد الظهر الأربعاء",
        "Thursday Afternoon": "بعد الظهر الخميس",
        "Friday Afternoon": "بعد الظهر الجمعة",
        "External log ID must be unique per fingerprint device.": "يجب أن يكون معرّف السجل الخارجي فريداً لكل جهاز بصمة.",
        "Device log external ID must be unique per device.": "يجب أن يكون المعرّف الخارجي لسجل الجهاز فريداً لكل جهاز.",
        "Daily status must be unique per employee and date.": "يجب أن تكون الحالة اليومية فريدة لكل موظف وتاريخ.",
        "HTTP listening token must be unique.": "يجب أن يكون رمز الاستقبال HTTP فريداً.",
        "Missing checkout flagged after scheduled end of work day.": "تم تمييز الانصراف غير المسجّل بعد نهاية يوم العمل المجدول.",
        "Missing checkout (activity summary)": "انصراف غير مسجّل (ملخص النشاط)",
        "Employee has check-in without checkout past tolerance.": "الموظف لديه حضور مسجّل دون انصراف بعد تجاوز السماحية.",
        "OK": "موافق",
        "No employee linked to user.": "لا يوجد موظف مربوط بالمستخدم.",
        "Invalid punch type.": "نوع التسجيل غير صالح.",
        "This punch was already recorded.": "تم تسجيل هذه العملية مسبقاً.",
        "You must check in before using this punch.": "يجب تسجيل الحضور قبل استخدام هذا التسجيل.",
        "You are not currently on break.": "أنت لست في استراحة حالياً.",
        "Home PIN check-in is only allowed on home schedule days.": "تسجيل الحضور برمز PIN من المنزل مسموح فقط في أيام العمل عن بُعد.",
        "Invalid PIN code.": "رمز PIN غير صالح.",
        "Not allowed to check attendance for another employee.": "غير مسموح بتسجيل حضور موظف آخر.",
        "Employee not found.": "الموظف غير موجود.",
    },
    "hr_overtime_payroll": {
        "Overtime": "العمل الإضافي",
    },
    "hr_holidays_custom_ext": {
        "A refusal reason is required.": "يجب إدخال سبب الرفض.",
        "A requester must be set before submitting.": "يجب تحديد مقدّم الطلب قبل الإرسال.",
        "Allocation Origin": "مصدر التخصيص",
        "Annual Grant": "منحة سنوية",
        "Annual Leave %s": "إجازة سنوية %s",
        "Annual Leave Carryover": "ترحيل الإجازة السنوية",
        "Annual Leave Carryover Complete": "اكتمل ترحيل الإجازة السنوية",
        "Annual Leave Carryover Log": "سجل ترحيل الإجازة السنوية",
        "Annual Leave Carryover Log: multi-company": "سجل ترحيل الإجازة السنوية: متعدد الشركات",
        "Annual Leave Days": "أيام الإجازة السنوية",
        "Annual Leave Days Per Year": "أيام الإجازة السنوية سنوياً",
        "Annual Leave Type": "نوع الإجازة السنوية",
        "Annual Leave: Carry Forward and Forfeit (Jan 1)": "الإجازة السنوية: الترحيل والمصادرة (١ يناير)",
        "Annual leave carryover for %(company)s (%(year)s): ": "ترحيل الإجازة السنوية لـ %(company)s (%(year)s): ",
        "Approval Trail": "مسار الاعتماد",
        "Maximum unused annual leave days carried into the new year per employee. ": "الحد الأقصى لأيام الإجازة السنوية غير المستخدمة المرحّلة إلى السنة الجديدة لكل موظف. ",
        "No Time Off manager is configured for final approval. ": "لم يتم تهيئة مسؤول الإجازات للاعتماد النهائي. ",
        "Sick leave renewal for %(company)s (%(year)s): ": "تجديد الإجازة المرضية لـ %(company)s (%(year)s): ",
        "Approval History": "سجل الموافقات",
        "Approval Step": "خطوة الموافقة",
        "Approvals": "الموافقات",
        "Approved requests cannot be cancelled.": "لا يمكن إلغاء الطلبات المعتمدة.",
        "As Of Date": "حتى تاريخ",
        "Calendar year this automated allocation belongs to.": "السنة الميلادية التي ينتمي إليها هذا التخصيص الآلي.",
        "Calendar year to create annual grants and carryover allocations for.": "السنة الميلادية لإنشاء المنح السنوية وتخصيصات الترحيل لها.",
        "Carried-Over Balance": "الرصيد المرحّل",
        "Carryover Days Capped": "أيام الترحيل المحددة بالسقف",
        "Carryover from %s": "ترحيل من %s",
        "Create an exceptional public holiday request": "إنشاء طلب عطلة رسمية استثنائية",
        "Create sick leave allocations for a selected year if they are missing.": "إنشاء تخصيصات الإجازة المرضية لسنة محددة إذا كانت مفقودة.",
        "Current Approver": "المعتمد الحالي",
        "Current-Year Balance": "رصيد السنة الحالية",
        "Days (0 = unlimited)": "أيام (٠ = بلا حد)",
        "Days Remaining": "الأيام المتبقية",
        "Days Used": "الأيام المستخدمة",
        "Decision Date": "تاريخ القرار",
        "Department Manager": "مدير الإدارة",
        "Employee Balance Summary": "ملخص أرصدة الموظفين",
        "Employee Leave Balance Summary": "ملخص رصيد إجازات الموظف",
        "End Date": "تاريخ الانتهاء",
        "Enter the refusal reason...": "أدخل سبب الرفض...",
        "Exceptional Holiday": "عطلة استثنائية",
        "Exceptional Holiday Approval Line": "سطر اعتماد العطلة الاستثنائية",
        "Exceptional Holiday Request": "طلب عطلة استثنائية",
        "Exceptional Holiday: multi-company": "العطلة الاستثنائية: متعدد الشركات",
        "Exceptional Holidays": "العطل الاستثنائية",
        "Exceptional Public Holiday Request": "طلب عطلة رسمية استثنائية",
        "Exceptional holiday %(ref)s requires your approval.": "العطلة الاستثنائية %(ref)s تتطلب اعتمادك.",
        "Exceptional holiday approval": "اعتماد عطلة استثنائية",
        "Exceptional holiday request submitted for approval.": "تم إرسال طلب العطلة الاستثنائية للاعتماد.",
        "Exceptional holidays, leave balance summary, annual sick leave renewal, and annual leave carryover": "العطل الاستثنائية، وملخص أرصدة الإجازات، وتجديد الإجازة المرضية السنوي، وترحيل الإجازة السنوية",
        "Explain why this request is refused...": "اشرح سبب رفض هذا الطلب...",
        "First Approval": "الاعتماد الأول",
        "Fixed annual leave days granted to each active employee at year start.": "عدد أيام الإجازة السنوية الثابتة الممنوحة لكل موظف نشط عند بداية السنة.",
        "Forfeit expired carryover and create annual leave allocations for a selected year.": "مصادرة الرصيد المرحّل المنتهي وإنشاء تخصيصات الإجازة السنوية لسنة محددة.",
        "Holiday Name": "اسم العطلة",
        "HR Holidays Custom Extensions": "توسعات الإجازات المخصصة للموارد البشرية",
        "HR Officer": "مسؤول الموارد البشرية",
        "Leave Approval - %s": "سجل اعتماد الإجازة - %s",
        "Leave Approval Log": "سجل اعتماد الإجازات",
        "Leave Approval Trail": "مسار اعتماد الإجازة",
        "Leave Balance Summary: multi-company": "ملخص رصيد الإجازات: متعدد الشركات",
        "Leave Type": "نوع الإجازة",
        "Leave empty to apply to all working schedules in the company.": "اتركه فارغاً لتطبيقه على جميع جداول العمل في الشركة.",
        "Manual": "يدوي",
        "Manual Carryover": "ترحيل يدوي",
        "Manual Renewal": "تجديد يدوي",
        "Manager Approved": "معتمد من المدير",
        "Max Carryover Days": "الحد الأقصى لأيام الترحيل",
        "Maximum unused annual leave days carried into the new year per employee. Set to 0 for no limit.": "الحد الأقصى لأيام الإجازة السنوية غير المستخدمة المرحّلة إلى السنة الجديدة لكل موظف. ضع ٠ لعدم وجود حد.",
        "No Time Off manager is configured for final approval. Assign at least one user to the Time Off Administrator group.": "لم يتم تهيئة مسؤول الإجازات للاعتماد النهائي. عيّن مستخدماً واحداً على الأقل في مجموعة مسؤولي الإجازات.",
        "No allocations were created or updated.": "لم يتم إنشاء أو تحديث أي تخصيصات.",
        "No approval chain could be resolved for this requester.": "تعذّر تحديد سلسلة الاعتماد لمقدّم هذا الطلب.",
        "No pending approval step found.": "لم يُعثر على خطوة اعتماد معلّقة.",
        "No public holiday record is linked yet.": "لا يوجد سجل عطلة رسمية مرتبط بعد.",
        "Number of sick leave days allocated per active employee on annual renewal.": "عدد أيام الإجازة المرضية المخصصة لكل موظف نشط عند التجديد السنوي.",
        "Number of sick leave days allocated to each active employee on annual renewal.": "عدد أيام الإجازة المرضية المخصصة لكل موظف نشط عند التجديد السنوي.",
        "Only cancelled or refused requests can be reset to draft.": "يمكن إعادة الطلبات الملغاة أو المرفوضة فقط إلى المسودة.",
        "Only draft requests can be edited.": "يمكن تعديل طلبات المسودة فقط.",
        "Only draft requests can be submitted.": "يمكن إرسال طلبات المسودة فقط.",
        "Origin Year": "سنة المنشأ",
        "Please refuse one time off request at a time.": "يرجى رفض طلب إجازة واحد في كل مرة.",
        "Print Approval Log": "طباعة سجل الاعتماد",
        "Public Holiday": "عطلة رسمية",
        "Public holiday created and is now active for attendance and overtime.": "تم إنشاء العطلة الرسمية وهي الآن فعّالة للحضور والعمل الإضافي.",
        "Refusal Reason": "سبب الرفض",
        "Refusal Reason:": "سبب الرفض:",
        "Refuse Exceptional Holiday": "رفض العطلة الاستثنائية",
        "Refuse Exceptional Holiday Request": "رفض طلب العطلة الاستثنائية",
        "Refuse Request": "رفض الطلب",
        "Refuse Time Off": "رفض طلب الإجازة",
        "Refuse Time Off Request": "رفض طلب الإجازة",
        "Renewal Year": "سنة التجديد",
        "Renewal year must be between 2000 and 2100.": "يجب أن تكون سنة التجديد بين ٢٠٠٠ و٢١٠٠.",
        "Request refused by %(user)s: %(reason)s": "تم رفض الطلب من قِبل %(user)s: %(reason)s",
        "Requested By": "مقدّم الطلب",
        "Requester": "مقدّم الطلب",
        "Requests go through manager and HR approval before becoming a live public holiday.": "تمر الطلبات باعتماد المدير والموارد البشرية قبل أن تصبح عطلة رسمية فعّالة.",
        "Run Annual Leave Carryover": "تشغيل ترحيل الإجازة السنوية",
        "Run Carryover": "تشغيل الترحيل",
        "Run Carryover Now": "تشغيل الترحيل الآن",
        "Run Now": "تشغيل الآن",
        "Run Renewal": "تشغيل التجديد",
        "Run Sick Leave Renewal": "تشغيل تجديد الإجازة المرضية",
        "Scheduled": "مجدول",
        "Second Approval": "الاعتماد الثاني",
        "Sick Leave": "إجازة مرضية",
        "Sick Leave %s": "إجازة مرضية %s",
        "Sick Leave Days Per Year": "أيام الإجازة المرضية سنوياً",
        "Sick Leave Renewal": "تجديد الإجازة المرضية",
        "Sick Leave Renewal Complete": "اكتمل تجديد الإجازة المرضية",
        "Sick Leave Renewal Log": "سجل تجديد الإجازة المرضية",
        "Sick Leave Renewal Log: multi-company": "سجل تجديد الإجازة المرضية: متعدد الشركات",
        "Sick leave renewal for %(company)s (%(year)s): %(processed)s employees processed, %(created)s allocations created, %(skipped)s skipped.": "تجديد الإجازة المرضية لـ %(company)s (%(year)s): تمت معالجة %(processed)s موظفاً، وإنشاء %(created)s تخصيصاً، وتخطي %(skipped)s.",
        "Start Date": "تاريخ البداية",
        "Submitted": "مُرسَل",
        "Target Year": "السنة المستهدفة",
        "Target year must be between 2000 and 2100.": "يجب أن تكون السنة المستهدفة بين ٢٠٠٠ و٢١٠٠.",
        "The end date must be on or after the start date.": "يجب أن يكون تاريخ الانتهاء في نفس يوم البداية أو بعده.",
        "The selected approval step does not belong to this request.": "خطوة الاعتماد المحددة لا تنتمي إلى هذا الطلب.",
        "Time Off Request": "طلب إجازة",
        "Time Off Type": "نوع الإجازة",
        "Time Off: Renew Annual Sick Leave Allocations (Jan 1)": "الإجازات: تجديد تخصيصات الإجازة المرضية السنوية (١ يناير)",
        "Time off request must be confirmed or validated in order to refuse it.": "يجب أن يكون طلب الإجازة مؤكداً أو معتمداً لرفضه.",
        "Time off type used for annual grants and carryover allocations.": "نوع الإجازة المستخدم للمنح السنوية وتخصيصات الترحيل.",
        "Time off type used for annual leave grants and carryover.": "نوع الإجازة المستخدم لمنح الإجازة السنوية والترحيل.",
        "To Approve": "بانتظار الاعتماد",
        "Total Accrued": "إجمالي المستحق",
        "Total Available": "إجمالي المتاح",
        "Trail Steps": "خطوات المسار",
        "Trigger": "آلية التشغيل",
        "Upper Manager": "المدير الأعلى",
        "Upper Manager Approved": "معتمد من المدير الأعلى",
        "Unused balance above the company carryover limit that was not carried forward.": "الرصيد غير المستخدم الذي يتجاوز حد الترحيل في الشركة ولم يُرحَّل.",
        "Working Hours": "ساعات العمل",
        "Year": "السنة",
        "Year Carryover": "ترحيل سنوي",
        "You are not allowed to refuse this request.": "غير مسموح لك برفض هذا الطلب.",
        "Annual Sick Leave Days": "أيام الإجازة المرضية السنوية",
        "Last Annual Leave Carryover": "آخر ترحيل للإجازة السنوية",
        "Last Carryover Run": "آخر تشغيل للترحيل",
        "Last Carryover Summary": "ملخص آخر ترحيل",
        "Last Renewal Run": "آخر تشغيل للتجديد",
        "Last Renewal Summary": "ملخص آخر تجديد",
        "Last Sick Leave Renewal": "آخر تجديد للإجازة المرضية",
    },
}


def should_skip(msgid: str) -> bool:
    if SKIP_PATTERN.match(msgid):
        return True
    if msgid.startswith("hr.") or msgid.startswith("face.") or msgid.startswith("fingerprint."):
        return True
    if msgid.startswith("project.") or msgid.startswith("res.config."):
        return True
    if msgid.startswith("resource.calendar."):
        return True
    return False


def translate(msgid: str, module: str) -> str:
    if msgid in TRANSLATIONS:
        return TRANSLATIONS[msgid]
    extra = EXTRA_BY_MODULE.get(module, {})
    if msgid in extra:
        return extra[msgid]
    # Preserve English for demo-only names
    if msgid.startswith("Demo OT"):
        return msgid
    return msgid  # fallback: keep English, flagged below


def po_escape(text: str) -> str:
    return text.replace('\\', '\\\\').replace('"', '\\"')


def generate_po(module: str, msgids: list[str]) -> tuple[str, list[str]]:
    date = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M+0000')
    lines = [PO_HEADER.format(date=date)]
    missing = []
    for msgid in sorted(set(msgids)):
        if should_skip(msgid):
            continue
        msgstr = translate(msgid, module)
        if msgstr == msgid and not msgid.startswith("Demo"):
            missing.append(msgid)
        lines.append(f'\n#. module: {module}')
        lines.append(f'msgid "{po_escape(msgid)}"')
        lines.append(f'msgstr "{po_escape(msgstr)}"')
    return '\n'.join(lines) + '\n', missing


def main():
    modules = [
        'hr_attendance_custom_ext',
        'hr_holidays_custom_ext',
        'hr_overtime_management',
        'hr_overtime_payroll',
        'project_custom_ext',
    ]
    all_missing: dict[str, list[str]] = {}
    for module in modules:
        extracted_path = ROOT / 'extra_addons' / module / 'i18n' / '_extracted_strings.json'
        if not extracted_path.exists():
            print(f'Skip {module}: no extracted strings')
            continue
        msgids = json.loads(extracted_path.read_text(encoding='utf-8'))
        content, missing = generate_po(module, msgids)
        out_path = ROOT / 'extra_addons' / module / 'i18n' / 'ar.po'
        out_path.write_text(content, encoding='utf-8')
        all_missing[module] = missing
        print(f'{module}: wrote {out_path} ({len(msgids) - len(missing)} translated, {len(missing)} fallback)')

    report = ROOT / 'scripts' / 'i18n_missing_report.txt'
    report.parent.mkdir(parents=True, exist_ok=True)
    with report.open('w', encoding='utf-8') as fh:
        for module, missing in all_missing.items():
            if missing:
                fh.write(f'\n=== {module} ({len(missing)} untranslated) ===\n')
                for m in sorted(missing):
                    fh.write(f'  - {m}\n')
    print(f'Missing report: {report}')


if __name__ == '__main__':
    main()
