{
    'name': 'HR Holidays Custom Extensions',
    'version': '19.0.1.3.10',
    'category': 'Human Resources/Time Off',
    'summary': 'Exceptional holidays, leave balance summary, annual sick leave renewal, and annual leave carryover',
    'author': 'Custom',
    'depends': [
        'hr_holidays',
        'mail',
        'hr',
        'hr_overtime_management',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/hr_leave_type_data.xml',
        'data/ir_cron_data.xml',
        'data/ir_cron_annual_leave_carryover.xml',
        'views/hr_exceptional_holiday_views.xml',
        'views/hr_leave_views.xml',
        'views/hr_leave_approval_report_views.xml',
        'views/hr_leave_balance_summary_views.xml',
        'views/hr_sick_leave_renewal_log_views.xml',
        'views/hr_annual_leave_carryover_log_views.xml',
        'views/hr_holidays_menus.xml',
        'views/res_config_settings_views.xml',
        'wizard/hr_exceptional_holiday_refuse_wizard_views.xml',
        'wizard/hr_leave_refuse_wizard_views.xml',
        'wizard/hr_sick_leave_renewal_wizard_views.xml',
        'wizard/hr_annual_leave_carryover_wizard_views.xml',
        'report/hr_leave_approval_report.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
